### ISSUE TITLE
Failed to load mod:  NoClassDefFoundError: mindustry/plugin/Plugin

### ISSUE THREAD

**Issue by CatEricka** [Astro36/mindustry-pause-plugin#1]
```log4j
[07-26-2021 22:37:57] [E] Failed to load mod file config/mods/mindustry-pause-plugin.jar. Skipping.
[07-26-2021 22:37:57] [E] java.lang.NoClassDefFoundError: mindustry/plugin/Plugin
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at mindustry.mod.Mods.loadMod(Mods.java:705)
        at mindustry.mod.Mods.loadMod(Mods.java:620)
        at mindustry.mod.Mods.load(Mods.java:275)
        at mindustry.Vars.init(Vars.java:288)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:57)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:66)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: java.lang.ClassNotFoundException: mindustry.plugin.Plugin
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 19 more

[07-26-2021 22:37:59] [I] Server loaded. Type 'help' for help.
```

**Comment by CatEricka** [comment]
```
 Version: Mindustry 6-release official / build 126.2
 Java Version: 11.0.10
```

**Comment by Astro36** [comment]
This plugin is deprecated since [Mindustry v105(6.0 Build 105)](https://github.com/Anuken/Mindustry/commit/88608b3f889d4ec2cfe54f1561f64f7f89de300a).

Use official server pause command instead: `$ pause <on/off>`
